#define LITERAL 3

#define SIMPLE_EXPRESSION 1 + 2

#define SIMPLE_EXPRESSION_WITH_PARENTHESIS (1 + 2)

#define SIMPLE_EXPRESSION_WITH_PARENTHESIS_AND_UNARY -(1 + 2)

#define COMPLEX_EXPRESION (1 + 2) * 3 << 1

#define COMPLEX_EXPRESION_REF (1 + 2) * SIMPLE_EXPRESSION

#define TEXT "Hello World"

#define TEXT_WITH_ESCAPE "Hello \"World\""

#define FLOAT_EXPRESION (1.3 + 2.6) 


